### ISSUE TITLE
Fig does 'nothing' and fig doctor reports no socket file in tmp (Linux) 

### ISSUE THREAD

**Issue by jfy133** [withfig/fig#1819]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

Ping @mribeirodantas who has been helping me with this :)

Sounds sort of similar to this: https://github.com/withfig/fig/issues/1798 but reports a different error.

```
$ fig doctor

✘ Figterm: No file at path /tmp/figterm-86a3eb97-0b79-4636-968b-0f00fac496db.socket


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

And no dropdown menu etc. appears.

### Environment

```yaml
### Details:
|OS|Fig|Shell|
|-|-|-|
|Linux 5.15.0-48-generic|fig_desktop 2.5.1
|/usr/bin/bash|
fig diagnostic

# Fig Diagnostics
## Fig details:
  - Fig version: 
## Hardware Info:
  - Model Name: cpu0
  - Model Identifier: GenuineIntel
  - Chip: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  - Cores: 4
  - Memory: 16417468 KB
## OS Info:
  - Linux 5.15.0-48-generic
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /home/jfellows
  - CLI Installed: true
  - Executable Location: /home/jfellows/.local/bin/fig
  - Current Window ID: 
  - Active Process: 
  - Terminal: <unknown>
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - TERM_SESSION_ID=86a3eb97-0b79-4636-968b-0f00fac496db
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_TERM=1
    - FIG_TERM_VERSION=5.2.0
    - TERM=xterm-256color
    - FIG_PID=3417
    - PATH=/home/jfellows/gems/bin:/home/jfellows/.conda/condabin:/home/jfellows/bin/nextflow/bin/:/home/jfellows/bin/ont-guppy-cpu/bin/:/home/jfellows/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/jfellows/.local/bin:/home/jfellows/.fig/bin:/var/lib/flatpak/exports/bin:/home/jfellows/.npm/bin
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: Unknown command
  - Hyper: Unknown command
  - Visual Studio Code: Unknown command
  - Docker:
```
