### ISSUE TITLE
Updating to VSCode 1.72.0 breaks autocomplete

### ISSUE THREAD

**Issue by ryanscherler** [withfig/fig#1883]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

It seems all of a sudden Fig stopped working in the integrated terminal of VSCODE. Is this possibly related to a recent update to VSCODE itself?

### Environment

```yaml
- SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: b93b3e1a-ff1d-49f7-847e-1ab5f78f21c5
    - FIG_PARENT: b93b3e1a-ff1d-49f7-847e-1ab5f78f21c5
    - FIG_SET_PARENT: b93b3e1a-ff1d-49f7-847e-1ab5f78f21c5
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

* M1 Mac
```
