### ISSUE TITLE
Cannot Use Fig on Ubuntu 20.04

### ISSUE THREAD

**Issue by StandinKP** [withfig/fig#1926]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Ubuntu 20.02

### Expected behaviour

Expected to run fig and fig doctor to run with no issues.
Using zsh on default Ubuntu terminal. Also checked all the configurations and all files.
Below are the zprofile, zshrc and `fig doctor --verbose` output attached. Thanks
[zprofile.txt](https://github.com/withfig/fig/files/9831863/zprofile.txt)
[zshrc.txt](https://github.com/withfig/fig/files/9831864/zshrc.txt)
[doctor_op.txt](https://github.com/withfig/fig/files/9831873/doctor_op.txt)

### Actual behaviour

It didn't work and fig fails to start.

### Environment

```yaml
### Details:
|OS|Fig|Shell|
|-|-|-|
|Linux 5.15.0-50-generic||/usr/bin/zsh|
fig diagnostic

# Fig Diagnostics
## NOTE: Fig is not running, run `fig launch` to get the full diagnostics
## Fig details:
## Hardware Info:
  - Model Name: cpu0
  - Model Identifier: GenuineIntel
  - Chip: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  - Cores: 6
  - Memory: 16551919 KB
## OS Info:
  - Linux 5.15.0-50-generic
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /home/kaushal
  - CLI Installed: true
  - Executable Location: /home/kaushal/.local/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Terminal: <unknown>
  - Environment Variables:
    - PATH=/usr/local/go/bin:/home/kaushal/go/bin:/home/kaushal/.bun/bin:/home/kaushal/.local/share/pnpm:/home/kaushal/.nvm/versions/node/v16.15.1/bin:/home/kaushal/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kaushal/.local/share/JetBrains/Toolbox/scripts:/home/kaushal/.fig/bin
    - TERM=xterm-256color
    - FIG_PID=318392
## Integrations:
```
