### ISSUE TITLE
fig : Depends: libwebkit2gtk-4.1-0 but it is not installable

### ISSUE THREAD

**Issue by Jefferson08** [withfig/fig#2429]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux Mint 20.3

### Expected behaviour

Install and run fig

### Actual behaviour

![image](https://user-images.githubusercontent.com/42618124/228590349-41ae09ba-e53e-444d-a855-3a49a6ce9207.png)

The following packages have unmet dependencies:
 fig : Depends: libwebkit2gtk-4.1-0 but it is not installable

### Steps to reproduce

Run install script:

`curl -SsL https://fig.io/install.sh | bash`

### Environment

```yaml
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una

Linux 5.11.0-46-generic x86_64
```
