### ISSUE TITLE
bug: fig breaks Visual Studio (MacOS) terminal

### ISSUE THREAD

**Issue by grantsanders** [withfig/fig#2431]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Venture 13.2

### Expected behaviour

I would expect visual studio's terminal to be unaffected by fig as it is not supported, but currently if Fig is running, the terminal no longer works correctly- the **clear** command doesn't work, and the screen will simultaneously think it's empty, and that it needs to go to the newest line- causing it to freak out and jump back and forth. 

Seems like all that would need to happen is Fig explicitly being told to ignore VS terminal, but I don't see any way to do that from the control panel. Tried disabling VSCode (and iTerm, Terminal, and hyper) no dice

### Actual behaviour

https://app.screencast.com/xRpIgQQT6KTg6

video of me demonstrating the issue- run clear multiple times, clears for a second but whenever new text is entered everything breaks.

### Environment

```yaml
g-details:
  - 2.15.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/grantsanders
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: f43b9f8a-04bd-443c-b1aa-ae6d26f795db
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/Frameworks/Mono.framework/Commands:/Applications/Visual Studio.app/Contents/MacOS:/opt/homebrew/bin:/Users/grantsanders/.fig/bin:/Users/grantsanders/.local/bin:/Users/grantsanders/.dotnet/tools:/Users/grantsanders/.dotnet/tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.microsoft.visual-studio
    - FIG_PID: 3706
    - FIG_SET_PARENT: f43b9f8a-04bd-443c-b1aa-ae6d26f795db
```
