### ISSUE TITLE
bug:Uninstall on Ubuntu 23.04 failed 

### ISSUE THREAD

**Issue by americanhanko** [withfig/fig#2502]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Ubuntu 23.04

### Expected behaviour

Expected `fig uninstall` to exit successfully. 

### Actual behaviour

Running `fig uninstall` resulted in errors

```
❯ fig uninstall

* Fig not working? Run fig doctor
* Autocomplete doesn't "feel" right? Watch https://fig.io/l/configuring-autocomplete
* Keep Fig but disable Autocomplete? Run fig settings autocomplete.disable true

✔ Do you want to continue uninstalling Fig? · Yes
Uninstalling Fig
fig_desktop: no process found
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  fig-headless
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 233150 files and directories currently installed.)
Removing fig-headless (2.15.0) ...
Uninstalling additional components...
runuser: user ehanko ehanko ehanko does not exist or the user entry does not contain all the required fields
runuser: user ehanko ehanko ehanko does not exist or the user entry does not contain all the required fields
error: Failed to uninstall properly
```

My user exists on the system:

```
❯ id -a
uid=1000(ehanko) gid=1000(ehanko) groups=1000(ehanko),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare)
```

### Steps to reproduce

1. Install fig on Ubuntu 23.04
2. Uninstall fig using `fig uninstall`

### Environment

```yaml
❯ lsb_release --all; uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
Linux latimeria 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```
