### ISSUE TITLE
not working with core shell

### ISSUE THREAD

**Issue by ginixsan** [withfig/fig#2514]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 11.7.6 (20G1231)

### Expected behaviour

Would like to see it working on [core shell](https://codinn.com/shell/ )

### Actual behaviour

It's not working. It works on terminal but when I go into core shell it doesn't show although if running fig doctor says everything is ok.

### Environment

```yaml
ig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 11.7.6 (20G1231)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/ginixsan
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 0ded6121-0a34-4f49-adef-0d17a100ccc8
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /usr/local/Caskroom/miniconda/base/bin:/usr/local/Caskroom/miniconda/base/condabin:/usr/local/sbin:/Users/ginixsan/.nvm/versions/node/v8.1.0/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/ginixsan/.fig/bin:/Users/ginixsan/.local/bin:/Users/ginixsan/.local/share/fig/plugins/git-flow:/Users/ginixsan/.local/share/fig/plugins/tumult.plugin.zsh_unixorn/bin:/usr/local/opt/go/bin:/usr/local/share/npm/bin:/Users/ginixsan/.local/share/fig/plugins/blackbox/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 41852
    - FIG_SET_PARENT: 0ded6121-0a34-4f49-adef-0d17a100ccc8
```
